config/routes.rb
Rails.application.routes.draw do
  resources :toys
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/cats" => "cats#index"
  get "/cats/new" => "cats#new"
  get "/cats/:id/edit" => "cats#edit"
  get "/cats/:id" => "cats#show"
  post "/cats" => "cats#create"
  patch "/cats/:id" => "cats#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render 'cats/index'
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render 'cats/show'
  end

  def new
    render 'cats/new'
  end

  def create
    cat = Cat.new
    cat.name = params[:name]
    cat.age = params[:age]
    cat.image_url = params[:image_url]
    cat.save
    redirect_to "/cats/" + cat.id.to_s
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render 'cats/edit'
  end

  def update
    cat = Cat.find_by(id: params[:id])
    cat.name = params[:name]
    cat.image_url = params[:image_url]
    cat.age = params[:age]
    cat.save

    redirect_to "/cats"
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: %i[ show edit update destroy ]

  # GET /toys or /toys.json
  def index
    @toys = Toy.all
  end

  # GET /toys/1 or /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys or /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to toy_url(@toy), notice: "Toy was successfully created." }
        format.json { render :show, status: :created, location: @toy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1 or /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to toy_url(@toy), notice: "Toy was successfully updated." }
        format.json { render :show, status: :ok, location: @toy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1 or /toys/1.json
  def destroy
    @toy.destroy

    respond_to do |format|
      format.html { redirect_to toys_url, notice: "Toy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def toy_params
      params.require(:toy).permit(:name, :description, :price, :cat_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/cats/edit.html.erb
<h1> YO </h1>
<form action="/cats/<%= @cat.id %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <p>Name: <input type="text" name="name" value="<%= @cat.name %>">
  <p>Image: <input type="text" name="image_url" value="<%= @cat.image_url %>">
  <p>age: <input type="text" name="age" value="<%= @cat.age %>">
  <input type="submit">
</form>

app/views/cats/index.html.erb
<h1> YO </h1>
<% @cats.each do |cat| %>
<p> Name: <%= cat.name%></p>
<p> Age: <%= cat.age%> </p>
<p> Id: <%= cat.id%> </p>
<img src="<%= cat.image_url %>">
<br />
<form action="http://localhost:3000/cats/<%=cat.id%>">
    <input type="submit" value="View Cat" />
</form>
<form action="http://localhost:3000/cats/<%=cat.id%>/edit">
    <input type="submit" value="Edit Cat" />
</form>
<% end %>

app/views/cats/new.html.erb
<h1> YO </h1>
<form action="/cats" method="post">
<p>Name: <input type="text" name="name">
<p>Age <input type="text" name="age">
<p>Image_url: <input type="text" name="image_url">
<input type="submit">
</form>

app/views/cats/show.html.erb
<h1> YO </h1>
<p> Name: <%= @cat.name %> </p>
<p> Age: <%= @cat.age %> </p>
<img src="<%= @cat.image_url %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <a href="/cats"> Home </a> |
  <a href="/cats/new"> New Cat </a>
    <%= yield %>
  </body>
</html>

app/views/toys/_form.html.erb
<%= form_with(model: toy) do |form| %>
  <% if toy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
        <% toy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :cat_id, style: "display: block" %>
    <%= form.text_field :cat_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/toys/_toy.html.erb
<div id="<%= dom_id toy %>">
  <p>
    <strong>Name:</strong>
    <%= toy.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= toy.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= toy.price %>
  </p>

  <p>
    <strong>Cat:</strong>
    <%= toy.cat_id %>
  </p>

</div>

app/views/toys/edit.html.erb
<h1>Editing toy</h1>

<%= render "form", toy: @toy %>

<br>

<div>
  <%= link_to "Show this toy", @toy %> |
  <%= link_to "Back to toys", toys_path %>
</div>

app/views/toys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Toys</h1>

<div id="toys">
  <% @toys.each do |toy| %>
    <%= render toy %>
    <p>
      <%= link_to "Show this toy", toy %>
    </p>
  <% end %>
</div>

<%= link_to "New toy", new_toy_path %>

app/views/toys/new.html.erb
<h1>New toy</h1>

<%= render "form", toy: @toy %>

<br>

<div>
  <%= link_to "Back to toys", toys_path %>
</div>

app/views/toys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @toy %>

<div>
  <%= link_to "Edit this toy", edit_toy_path(@toy) %> |
  <%= link_to "Back to toys", toys_path %>

  <%= button_to "Destroy this toy", @toy, method: :delete %>
</div>